name: vitpose-ekf
channels:
  - conda-forge
  - opensim-org
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.25
  - scipy=1.15
  - biorbd=1.11.2
  - opencv
  - lxml
  - ezc3d
  - matplotlib
  - pandas
  - plotly
  - black
  - isort=9.0.2
  - flake8
  - pip:
      - git+https://github.com/pyomeca/biobuddy.git@85ec552f4c73152590336ca571c1a32ed911c75a
      - pyorerun
